systems:
- name: frontier
  descr: Frontier system.
  hostnames: ['frontier\d+']
  modules_system: lmod
  partitions:
  - name: batch
    descr: Use nodes from the Slurm partition containing MI250X nodes
    scheduler: slurm
    launcher: local
    # If you care about GPU binding or cores per task, you must set it here, it is not handled by tests
    # Tests only handle -N/-n/--ntasks-per-node
    access: ['-A gen243 -p batch']
    environs: ['pmix_test']

environments:
- name: pmix_test

